"use client";

import { useMemo, useState } from "react";

function clamp(v: number) {
  return Number.isFinite(v) ? Math.max(0, v) : 0;
}

export default function ClimateImpactInvestmentROICalculator() {
  const [initialInvestment, setInitialInvestment] = useState<number>(500000);
  const [annualCashflow, setAnnualCashflow] = useState<number>(60000);
  const [years, setYears] = useState<number>(7);
  const [exitValue, setExitValue] = useState<number>(650000);

  const result = useMemo(() => {
    const initial = clamp(initialInvestment);
    const cash = clamp(annualCashflow);
    const y = clamp(years);
    const exit = clamp(exitValue);

    const totalCashflows = cash * y;
    const totalReturn = totalCashflows + exit - initial;
    const roiPct = initial > 0 ? (totalReturn / initial) * 100 : null;

    return {
      initial,
      cash,
      years: y,
      exit,
      totalCashflows,
      totalReturn,
      roiPct,
    };
  }, [initialInvestment, annualCashflow, years, exitValue]);

  return (
    <div className="space-y-6">
      <p className="text-sm opacity-80">
        Estimate a simple ROI for climate impact investments based on expected annual cashflow impact, holding period,
        and exit value. This is a planning estimate (not IRR).
      </p>

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="block text-sm font-medium">Initial Investment ($)</label>
          <input
            className="input"
            type="number"
            min={0}
            step="0.01"
            value={initialInvestment}
            onChange={(e) => setInitialInvestment(Number(e.target.value))}
          />
          <p className="mt-1 text-xs opacity-70">
            Upfront capital deployed at the start of the investment.
          </p>
        </div>

        <div>
          <label className="block text-sm font-medium">Annual Cashflow Impact ($)</label>
          <input
            className="input"
            type="number"
            min={0}
            step="0.01"
            value={annualCashflow}
            onChange={(e) => setAnnualCashflow(Number(e.target.value))}
          />
          <p className="mt-1 text-xs opacity-70">
            Expected annual profit or savings generated by the project.
          </p>
        </div>

        <div>
          <label className="block text-sm font-medium">Holding Period (years)</label>
          <input
            className="input"
            type="number"
            min={0}
            step="1"
            value={years}
            onChange={(e) => setYears(Number(e.target.value))}
          />
          <p className="mt-1 text-xs opacity-70">
            Duration you plan to hold the investment before exiting.
          </p>
        </div>

        <div>
          <label className="block text-sm font-medium">Exit Value ($)</label>
          <input
            className="input"
            type="number"
            min={0}
            step="0.01"
            value={exitValue}
            onChange={(e) => setExitValue(Number(e.target.value))}
          />
          <p className="mt-1 text-xs opacity-70">
            Expected sale value or terminal value at the end of the holding period.
          </p>
        </div>
      </div>

      <div className="rounded-lg border p-4 space-y-2">
        <p className="font-semibold">
          Total Cashflows: $
          {result.totalCashflows.toLocaleString(undefined, { maximumFractionDigits: 0 })}
        </p>
        <p className="font-semibold">
          Total Return: $
          {result.totalReturn.toLocaleString(undefined, { maximumFractionDigits: 0 })}
        </p>

        {result.roiPct === null ? (
          <p className="text-sm opacity-80">
            ROI is unavailable because initial investment is $0.
          </p>
        ) : (
          <p className="font-semibold text-lg">
            ROI: {result.roiPct.toFixed(2)}%
          </p>
        )}

        <p className="text-sm opacity-80">
          Inputs — Initial: ${result.initial.toLocaleString()}, Annual cashflow: $
          {result.cash.toLocaleString()}, Years: {result.years.toLocaleString()}, Exit: $
          {result.exit.toLocaleString()}
        </p>
      </div>
    </div>
  );
}
